import type { Metadata } from 'next';
import './globals.css';
import Footer from '@/features/utils/Footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="min-h-screen">
        {children}
        <Footer/>
      </body>
    </html>
  );
}
